language: ruby
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
notifications:
  recipients:
    - memde@engineyard.com
  webhooks:
    urls:
      - https://ensemble.engineyard.com/travis
    on_success: always
    on_failure: always
    on_start: true
