language: ruby
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
notifications:
  email: false
  webhooks:
    urls:
      - https://ensemble.engineyard.com/travis
    on_success: always
    on_failure: always
    on_start: true

script: bundle exec rake
